package com.lanxiang.mybatis.model;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated Mon Aug 22 11:37:58 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.value
     *
     * @mbggenerated Mon Aug 22 11:37:58 CST 2016
     */
    private Double value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated Mon Aug 22 11:37:58 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated Mon Aug 22 11:37:58 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.value
     *
     * @return the value of message.value
     *
     * @mbggenerated Mon Aug 22 11:37:58 CST 2016
     */
    public Double getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.value
     *
     * @param value the value for message.value
     *
     * @mbggenerated Mon Aug 22 11:37:58 CST 2016
     */
    public void setValue(Double value) {
        this.value = value;
    }
}