package com.lanxiang.mybatis.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.id
     *
     * @mbggenerated Sat Apr 15 13:06:50 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.position
     *
     * @mbggenerated Sat Apr 15 13:06:50 CST 2017
     */
    private Long position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.name
     *
     * @mbggenerated Sat Apr 15 13:06:50 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.age
     *
     * @mbggenerated Sat Apr 15 13:06:50 CST 2017
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.id
     *
     * @return the value of User.id
     *
     * @mbggenerated Sat Apr 15 13:06:50 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.id
     *
     * @param id the value for User.id
     *
     * @mbggenerated Sat Apr 15 13:06:50 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.position
     *
     * @return the value of User.position
     *
     * @mbggenerated Sat Apr 15 13:06:50 CST 2017
     */
    public Long getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.position
     *
     * @param position the value for User.position
     *
     * @mbggenerated Sat Apr 15 13:06:50 CST 2017
     */
    public void setPosition(Long position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.name
     *
     * @return the value of User.name
     *
     * @mbggenerated Sat Apr 15 13:06:50 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.name
     *
     * @param name the value for User.name
     *
     * @mbggenerated Sat Apr 15 13:06:50 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.age
     *
     * @return the value of User.age
     *
     * @mbggenerated Sat Apr 15 13:06:50 CST 2017
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.age
     *
     * @param age the value for User.age
     *
     * @mbggenerated Sat Apr 15 13:06:50 CST 2017
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    public User() {
    }

    public User(Long position, String name, Integer age) {
        this.position = position;
        this.name = name;
        this.age = age;
    }
}