package com.lanxiang.model;

import com.lanxiang.util.UuidUtil;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_user_address.id
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_user_address.user_id
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_user_address.province
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_user_address.city
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_user_address.town
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    private String town;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column learn_user_address.detail
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_user_address.id
     *
     * @return the value of learn_user_address.id
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_user_address.id
     *
     * @param id the value for learn_user_address.id
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_user_address.user_id
     *
     * @return the value of learn_user_address.user_id
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_user_address.user_id
     *
     * @param userId the value for learn_user_address.user_id
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_user_address.province
     *
     * @return the value of learn_user_address.province
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_user_address.province
     *
     * @param province the value for learn_user_address.province
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_user_address.city
     *
     * @return the value of learn_user_address.city
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_user_address.city
     *
     * @param city the value for learn_user_address.city
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_user_address.town
     *
     * @return the value of learn_user_address.town
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_user_address.town
     *
     * @param town the value for learn_user_address.town
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    public void setTown(String town) {
        this.town = town == null ? null : town.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column learn_user_address.detail
     *
     * @return the value of learn_user_address.detail
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column learn_user_address.detail
     *
     * @param detail the value for learn_user_address.detail
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    public void generateId() {
        if (this.id == null) {
            this.id = "aid_" + UuidUtil.getUuid();
        }
    }

    @Override
    public String toString() {
        return "Address{" +
                "id='" + id + '\'' +
                ", userId='" + userId + '\'' +
                ", province='" + province + '\'' +
                ", city='" + city + '\'' +
                ", town='" + town + '\'' +
                ", detail='" + detail + '\'' +
                '}';
    }
}