// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: soutmessage.proto

package com.lanxiang.protobuf;

public interface GreetingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lanxiang.protobuf.Greeting)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string from = 2;</code>
   */
  java.lang.String getFrom();
  /**
   * <code>optional string from = 2;</code>
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>optional string to = 3;</code>
   */
  java.lang.String getTo();
  /**
   * <code>optional string to = 3;</code>
   */
  com.google.protobuf.ByteString
      getToBytes();

  /**
   * <code>optional string content = 4;</code>
   */
  java.lang.String getContent();
  /**
   * <code>optional string content = 4;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
