// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: soutmessage.proto

package com.lanxiang.protobuf;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.lanxiang.protobuf.Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>optional string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 age = 3;</code>
   */
  int getAge();
}
