// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: soutmessage.proto

package com.lanxiang.protobuf;

public final class Soutmessage {
  private Soutmessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanxiang_protobuf_Greeting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanxiang_protobuf_Greeting_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_lanxiang_protobuf_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_lanxiang_protobuf_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021soutmessage.proto\022\025com.lanxiang.protob" +
      "uf\"A\n\010Greeting\022\n\n\002id\030\001 \001(\005\022\014\n\004from\030\002 \001(\t" +
      "\022\n\n\002to\030\003 \001(\t\022\017\n\007content\030\004 \001(\t\"/\n\006Person\022" +
      "\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\013\n\003age\030\003 \001(\005B\002" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_lanxiang_protobuf_Greeting_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_lanxiang_protobuf_Greeting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanxiang_protobuf_Greeting_descriptor,
        new java.lang.String[] { "Id", "From", "To", "Content", });
    internal_static_com_lanxiang_protobuf_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_lanxiang_protobuf_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_lanxiang_protobuf_Person_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
