package com.lanxiang.mapper;

import com.lanxiang.model.Address;
import com.lanxiang.model.AddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_user_address
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    int countByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_user_address
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    int deleteByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_user_address
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_user_address
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    int insert(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_user_address
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    int insertSelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_user_address
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    List<Address> selectByExample(AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_user_address
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    Address selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_user_address
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    int updateByExampleSelective(@Param("record") Address record, @Param("example") AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_user_address
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    int updateByExample(@Param("record") Address record, @Param("example") AddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_user_address
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    int updateByPrimaryKeySelective(Address record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table learn_user_address
     *
     * @mbggenerated Thu Sep 01 12:22:54 CST 2016
     */
    int updateByPrimaryKey(Address record);

    Address selectByUserId(int userId);
}